import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col overflow-hidden`}
      >
        <header className="bg-purple-900 p-4">
          <div className="flex items-center justify-between max-w-7xl mx-auto">
            <Link className="text-white" href="/"> Ana Sayfa</Link>
          </div>
        </header>
        <main className="flex-grow overflow-auto">
          <div className="h-full">
            {children}
          </div>
        </main>
        <footer className="bg-purple-900 text-white py-6">
          <div className="container mx-auto px-4">
            <div className="flex justify-between items-center">
              <div>
                <p>&copy; 2024 Mortablogoz. Tüm hakları saklıdır.</p>
              </div>
              <div>
                <Link href="/" className="hover:text-gray-300 mr-4">Ana Sayfa</Link>
                <Link href="/blog" className="hover:text-gray-300 mr-4">Blog</Link>
                <Link href="/iletisim" className="hover:text-gray-300">İletişim</Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
